version: '3.7'
services:
  mylims_frontend:
    build: .
    ports:
      - 3000:3000
    environment:
      BACKEND_HOST: mylims_backend
      BACKEND_PORT: 4000
      FILESYSTEM_HOST: mylims_filesystem
      FILESYSTEM_PORT: 5000
    networks:
      - mylims
      - local

networks:
  mylims:
    external:
      name: mylims
  local:
